### PR TITLE
Bundle SEAT GUI with jack tools and build on CI

### PR DESCRIPTION
**Pull request by alexdewar**
Hi @alastairhmoore.

I've finished up my side of things now, but Adrian will come and see you on Thurs. Now you can create a bundled directory with a `seat-gui.exe` file in it using `pyinstaller`. To do so, you run: `pyinstaller seat-gui.spec`

We've added a GitHub Action for it so that when you create a new release on GitHub, it will be build and uploaded as a release asset. See example here: https://github.com/AdrianDAlessandro/sap-elospheres-audiovisual-test/releases/tag/test_release

There are currently a looooot of dependencies, so the zip file is ~350MB and ~1GB when unzipped. Given that this meant the EXE was taking a long time to start (it has to self-extract every time), I switched to having the dependencies in a directory instead, which loads much faster. You can change it back if you prefer though! If you care enough, you could try removing unnecessary dependencies and maybe having a more minimal conda config purely for building the `pyinstaller` binary.

I've bundled jacktrip and the jack executables you use into the CI-generated build, so users no longer have to install them separately. If the path to jack/jacktrip in the config file doesn't exist, the Python code now falls back on using the bundled versions. Jacktrip is downloaded by GitHub Actions when building it, but annoyingly I couldn't make this process work for jack, because the only Windows binaries I could find were in an installer which I couldn't figure out how to extract from the command line. As a workaround, I've committed the relevant binaries into git, which I hate, but does the job for now. A better solution would be to install jack using the chocolatey package manager (which comes preinstalled on GitHub's runners), but their jack package wouldn't install for me, and it seems I'm not the only one: https://community.chocolatey.org/packages/jack#discussion

Unfortunately, I didn't have much luck with openMHA. I managed to install it in WSL, but for some reason the Python code couldn't connect to it and I didn't have time to look into why this was. Please let me know if things don't work for you though!

Most of this should work fine on macOS and Linux too, apart from the Windows-specific bits, obviously, though I didn't set up the CI to generate binaries for these platforms.

On another note, while I didn't have a chance to look at it, I think there's a high likelihood that you could bundle up your WSL dependencies using docker and make them available to users that way. Nowadays, docker for Windows uses WSL under the hood anyway, so there shouldn't be a performance penalty. As a first attempt, you could try manually installing the dependencies into a docker image and uploading it manually. I've found [this package](https://github.com/gabrieldemarmiesse/python-on-whales) to be useful for working with docker images from Python, but in the shorter term you could probably make your existing scripting work -- I *think* you should be able to run a docker image using the `wsl` command.

### CODE REVIEW

**Comment by alastairhmoore** [comment]
Hi @alexdewar 

Thank you for all the work you have put into this.  I’m not going to have the opportunity to test this properly before I meet Adrian tomorrow.  Having a  quick look through it mostly seems to make sense and looks good.

I have a quick question about the bundled versions of jackd.exe, jack_connect.ext and jack_disconnect.exe — could these by in a different folder - e.g. a ‘win_bin’ folder which is at the same level as ’seat’ rather than directly in the seat folder? I know you’d rather not have these exe files at all but since we need them it would be nice if they were kept separate from the seat code.

**Comment by alexdewar** [comment]
Sure thing. Done.

**Comment by alastairhmoore** [comment]
@alexdewar
I downloaded and extracted the zip file, then ran seat-gui.exe. After populating the dialogue box with the path to a known working csv file I get the following error
image

**Comment by alexdewar** [comment]
Arg, that's annoying. Sorry about that. It was definitely working at some point, so I'm not sure what's happened. I'll look into it now.

Tagging @AdrianDAlessandro.

**Comment by AdrianDAlessandro** [comment]
@alastairhmoore You will have to merge this PR into your repo and [Create a Release](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release) for these changes to be merged and the executable available on your repo.

There is one last change that could be made here: The change from Conda to pip-tools has drastically reduced the size of the executable (it is now under 100MB), so it could be possible to make it into a single, self-extracting, executable again and not require it to all be bundled in a zip, as it is now.

**Comment by alexdewar** [comment]
@alastairhmoore Just a reminder that this is still here if you want it!

**Pull request merged**
